### ISSUE TITLE
[BUG]-Empty string causes null reference Exception for XSigSerialToken

### ISSUE THREAD

**Issue by andrew-welker** [PepperDash/PepperDashCore#61]
**Describe the bug**
Trying to send an empty string over an XSig via the XSigSerialToken will fail with null reference exception
**Stacktrace**

Include a stack trace of the exception if possible.
```
[08:09:08.013]App 1:[zoomRoom] Error Deserializing feedback: System.ArgumentNullException: Value can not be null.
   at System.Text.Encoding.GetBytes(String s)
   at PepperDash.Core.Intersystem.Tokens.XSigSerialToken.GetBytes()
   at PepperDash.Core.Intersystem.XSigTokenStreamWriter.WriteXSigData(IEnumerable`1 tokens, Int32 offset)
   at PepperDash.Core.Intersystem.XSigTokenStreamWriter.WriteXSigData(IEnumerable`1 tokens)
   at PepperDash.Core.Intersystem.XSigTokenStreamWriter.WriteXSigData(XSigToken[] tokens)
   at PepperDash.Essentials.Devices.Common.VideoCodec.VideoCodecBase.GetXSigString(XSigToken[] tokenArray)
   at PepperDash.Essentials.Devices.Common.VideoCodec.VideoCodecBase.UpdateCallStatusXSig()
   at PepperDash.Essentials.Devices.Common.VideoCodec.VideoCodecBase.<>c__DisplayClass7.<LinkVideoCodecCallControlsToApi>b__4(Object sender, CodecCallStatusItemChangeEventArgs args)
   at PepperDash.Essentials.Devices.Common.VideoCodec.VideoCodecBase.OnCallStatusChange(CodecActiveCallItem item)
   at PepperDash.Essentials.Devices.Common.VideoCodec.ZoomRoom.ZoomRoom.DeserializeResponse(String response)
   at PepperDash.Essentials.Devices.Common.VideoCodec.ZoomRoom.ZoomRoom.ProcessMessage(String message)
   at PepperDash.Essentials.Devices.Common.VideoCodec.ZoomRoom.ZoomRoom.ProcessQueue()
   at PepperDash.Essentials.Devices.Common.VideoCodec.ZoomRoom.ZoomRoom.<.ctor>b__0(Object o)
   at Crestron.SimplSharpPro.CrestronThread.UserThreadStartDelegateWrapper.Worker(Object notUsed)
   at Amib.Threading.Internal.WorkItem.ExecuteWorkItem()
   at Amib.Threading.Internal.WorkItem.Execute()
   at Amib.Threading.SmartThreadPool.ExecuteWorkItem(WorkItem workItem)
   at Amib.Threading.SmartThreadPool.ProcessQueuedItems()
```

**Expected behavior**
The correct XSig token is produced

**Comment by andrew-welker** [comment]
When using XSigSerialToken, check if the serial value is null prior to creating the token. This will prevent the null reference exception.
