### ISSUE TITLE
[BUG]-Stream Debug throws exception

### ISSUE THREAD

**Issue by ngenovese11** [PepperDash/PepperDashCore#93]
**Describe the bug**
When enabling stream debugging an exception is thrown

**Stacktrace**

Include a stack trace of the exception if possible.
```
PRO3>setdevicestreamdebug lights-com both

PRO3>[10:18:17.000]App 1:Saving debug settings
Error: SimplSharpPro.exe [App 1] # 2021-04-02 10:18:17  # CustomApplicationCMDProcessorThread: FormatException -    at System.Text.StringBuilder.FormatError()
   at System.Text.StringBuilder.AppendFormat(IFormatProvider provider, String format, Object[] args)
   at System.String.Format(IFormatProvider providerError: SimplSharpPro.exe [App 1] # 2021-04-02 10:18:17  # , String format, Object[] args)
   at System.String.Format(String format, Object[] args)
   at PepperDash.Core.Debug.Console(UInt32 level, String format, Object[] items)
   at PepperDash.Essentials.Core.DeviceManager.SetDeviceStreamDebugging(String s)
Error: SimplSharpPro.exe [App 1] # 2021-04-02 10:18:17  #    at PepperDash.Essentials.Core.DeviceManager.<Initialize>b__3(String s)
   at Crestron.SimplSharpProInternal.SimplSharpProManager.k()
```

**Comment by andrew-welker** [comment]
Can you provide the text of the command you were using?
