### ISSUE TITLE
[BUG]-GenericTcpIpClient throws a null reference exception if connection hasn't been established and disconnect is called

### ISSUE THREAD

**Issue by ndorin** [PepperDash/PepperDashCore#94]
**Describe the bug**
If an instance of a client has been trying to connect to a server, but has never done so successfully and the `Disconnect()` method is called, the `RetryTimer` throws a null reference exception in its `TimerCallbackFunction`

**Stacktrace**

Include a stack trace of the exception if possible.
```
84. Error: SimplSharpPro.exe [App 1] # 2021-04-22 15:30:06  # Exception:TimerCallbackFunction: - System.NullReferenceException: NullReferenceException
   at PepperDash.Core.GenericTcpIpClient.<WaitAndTryReconnect>b__0(Object o)
   at Crestron.SimplSharp.CTimer.a(Object A_0)
   at System.Threading.Timer.ring()

```

**Expected behavior**
We need to make sure we check `Client` for null in the callback function for `RetryTimer`.  We should also stop the timer when `Disconnect()` is called

**Comment by ndorin** [comment]
@hunterwbrock This issue is resolve in 1.0.46 of this library.  The next release of Essentials will be updated to include it as a dependency.
